"""empty message

Revision ID: 3d9d8d9325a2
Revises: efdc9e7dd228
Create Date: 2019-01-16 08:41:54.700433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9d8d9325a2'
down_revision = 'efdc9e7dd228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
