"""empty message

Revision ID: efdc9e7dd228
Revises: e2ec6c853d64
Create Date: 2019-01-16 08:31:28.096705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'efdc9e7dd228'
down_revision = 'e2ec6c853d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('status', sa.Integer(), nullable=False))
    op.drop_column('todos', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.drop_column('todos', 'status')
    # ### end Alembic commands ###
